//! The published status page.
//!
//! `spec/sql/duckdb/11-the-number.md` section 11.2 describes one page, generated by this command
//! and never edited by hand, with eleven numbers on it, each with a denominator and a provenance,
//! and no single headline percentage anywhere. This module writes that page.
//!
//! Three of the eleven have nothing behind them today: statement coverage, the five error levels
//! and the three resource ratios. They are printed under a heading that says so and names what
//! would produce each one, rather than being left off the page or printed as a zero. A zero is a
//! measurement and a missing measurement is not, and the difference between the two is the whole of
//! section 1.2.
//!
//! Function coverage is the fourth of those and it is measured now, but not by this command. The
//! sweep behind it is every generated call to every overload in the catalog put to both engines,
//! which is forty minutes, and this page comes out of a corpus run that takes a fraction of that.
//! So `rudb-compat coverage` writes one row down beside the pages and this page reads the most
//! recent one back and says when and where it was measured. A number carried from another run is
//! worth having and is not the same thing as a number out of this run, and the page says which it
//! is looking at.
//!
//! The provenance is gathered best effort. Every field that cannot be found says what it could not
//! find, because a page that refuses to be written because git is not on the machine is worse than
//! a page that says the commit is unknown, and a reader can tell the two apart.

use std::fmt;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::{SystemTime, UNIX_EPOCH};

use crate::conform::Reason;
use crate::coverage::{Coverage, Tally, Untested};
use crate::duckdb::{Duckdb, PINNED, PINNED_COMMIT, Pin};
use crate::engine::{Engine, HarnessError};
use crate::isolate::Isolated;
use crate::vendor;

/// Where the pages go when nobody says otherwise, relative to the crate root.
pub const DEST: &str = "target/report";

/// The file every run appends one row to, beside the pages.
pub const SERIES: &str = "series.tsv";

/// The columns of that file, in order.
///
/// Tab separated because this crate has one dependency and it is the engine, so there is no
/// serializer here and there is not going to be one. A tab separated file with a header is a table
/// awk and every spreadsheet already read.
pub const COLUMNS: [&str; 17] = [
    "when",
    "machine",
    "rudb",
    "rudb_commit",
    "compat_commit",
    "corpus_commit",
    "duckdb",
    "files",
    "attempted",
    "passed",
    "failed",
    "rate",
    "skip_excused",
    "skip_engine",
    "skip_harness",
    "skip_machine",
    "wrong_answers",
];

/// The file every function sweep appends one row to, beside the pages.
///
/// A file of its own rather than more columns on [`SERIES`], because the two runs happen at
/// different rates. A corpus run is minutes and goes on every commit, a sweep is most of an hour and
/// goes when somebody asks for it, and putting them in one table would mean a row with half of it
/// empty every time either one ran without the other.
pub const SWEEPS: &str = "coverage.tsv";

/// The columns of that file, in order.
pub const SWEEP_COLUMNS: [&str; 18] = [
    "when",
    "machine",
    "rudb",
    "rudb_commit",
    "compat_commit",
    "duckdb",
    "names",
    "names_passed",
    "names_failed",
    "names_untested",
    "overloads",
    "overloads_passed",
    "overloads_failed",
    "overloads_untested",
    "crashes",
    "no_boundary",
    "kind_not_called",
    "volatile",
];

/// Everything about the run that is not a number out of it.
///
/// Section 9.8 calls a percentage without this a rumour, and section 11.2 says the resource numbers
/// need it more than the correctness numbers do. It is gathered once at the top of a run and
/// carried to the page, so that every number on the page is under one of these and not under a
/// mixture of this machine now and that machine yesterday.
#[derive(Debug, Clone)]
pub struct Provenance {
    /// Seconds since the epoch, which is what the file name is built from.
    pub unix: u64,
    /// The same instant written out, in UTC.
    pub stamp: String,
    /// What the machine calls itself.
    pub host: String,
    /// The operating system, the processor and how many cores the run could see.
    pub platform: String,
    /// The rudb version, as the engine reports it.
    pub rudb: String,
    /// The rudb commit, read out of the lock file that pins it.
    pub rudb_commit: String,
    /// The commit of this harness, with a note when the tree it ran from was dirty.
    pub compat_commit: String,
    /// The DuckDB release and commit this project tracks.
    pub duckdb_pin: String,
    /// Where the DuckDB binary on this machine is, when there is one.
    pub duckdb_binary: String,
    /// What that binary calls itself.
    pub duckdb_version: String,
    /// The md5 of that binary, so that two runs claiming the same version can be told apart.
    pub duckdb_hash: String,
    /// Whether that binary is the commit this project tracks.
    ///
    /// Nothing on the page comes out of DuckDB yet, and this row is here from the start anyway,
    /// because the resource ratios that are coming are a comparison against whatever binary was on
    /// the machine and a ratio against another build is a ratio about another database.
    pub duckdb_pinned: String,
    /// The tag the corpus is fetched at.
    pub corpus_ref: String,
    /// The commit the corpus is at.
    pub corpus_commit: String,
    /// Where the corpus this run read is.
    pub corpus_path: String,
    /// Whether that is the fetched upstream corpus rather than some directory somebody named.
    ///
    /// A run over a directory of its own is a useful thing to have a page for and it is not the
    /// published number, and the page says which of the two it is in the first sentence about the
    /// corpus. Without this, a page from a narrowed down run reads exactly like the real one.
    pub upstream: bool,
    /// The seed, when anything in the run generated anything.
    pub seed: String,
}

impl Provenance {
    /// Look up everything about this machine and this checkout.
    ///
    /// `root` is the crate root, which is where the lock file and the fetched corpus are. `corpus`
    /// is the directory this run actually read, which is not always the fetched one because a run
    /// narrowing down a failure points at a directory of its own.
    #[must_use]
    pub fn gather(root: &Path, corpus: &Path, rudb: &str) -> Self {
        let unix = SystemTime::now().duration_since(UNIX_EPOCH).map_or(0, |d| d.as_secs());
        let upstream = corpus.starts_with(root.join(vendor::DEST));
        let duckdb = Duckdb::discover();
        let (binary, version, hash, pinned) = match &duckdb {
            Ok(db) => (
                db.binary().display().to_string(),
                db.version().to_owned(),
                md5_of(db.binary()),
                match db.pin() {
                    Pin::Pinned => {
                        "yes, this is the commit the grammar is vendored from".to_owned()
                    }
                    Pin::OtherCommit => {
                        format!("no, this is {PINNED} built at some other commit")
                    }
                    Pin::Fallback => "no, this is some other DuckDB".to_owned(),
                },
            ),
            Err(_) => {
                let missing = "no duckdb on this machine".to_owned();
                (missing.clone(), missing.clone(), missing.clone(), missing)
            }
        };
        Self {
            unix,
            stamp: stamp(unix),
            host: host(),
            platform: platform(),
            rudb: rudb.to_owned(),
            rudb_commit: locked(root).unwrap_or_else(|| "unknown".to_owned()),
            compat_commit: checkout(root),
            duckdb_pin: format!("{PINNED} at {}", short(PINNED_COMMIT)),
            duckdb_binary: binary,
            duckdb_version: version,
            duckdb_hash: hash,
            duckdb_pinned: pinned,
            corpus_ref: vendor::REF.to_owned(),
            corpus_commit: if upstream {
                vendor::commit(root).map_or_else(|_| "unknown".to_owned(), |c| short(&c).to_owned())
            } else {
                "none".to_owned()
            },
            corpus_path: corpus.display().to_string(),
            upstream,
            // There is no generator in this harness yet, so there is nothing for a seed to make
            // repeatable. The row is here because section 11.2 asks for it, and a row that says
            // what it is waiting for is how the next person finds where to put it.
            seed: "none, nothing in this run generates anything".to_owned(),
        }
    }

    /// The same, for a run that read no corpus.
    ///
    /// The function sweep builds its own calls out of the catalog, so the corpus rows on it are not
    /// unknown, they do not apply, and those are different things to say. Everything else about the
    /// machine and the two engines is gathered the same way, because that is what makes the sweep
    /// comparable to the corpus run beside it.
    #[must_use]
    pub fn of_machine(root: &Path, rudb: &str) -> Self {
        let mut p = Self::gather(root, Path::new("none"), rudb);
        p.corpus_commit = "none".to_owned();
        p.corpus_path = "none, this run generated its own calls".to_owned();
        p.seed = "none, the calls come from a fixed table of boundary values".to_owned();
        p
    }

    /// The name of the file this run's page goes in.
    ///
    /// The instant first so that a directory of them sorts into the order they were run in, and the
    /// machine after it so that two machines reporting in the same second do not overwrite each
    /// other. Both are needed: a series is only a series if the rows are comparable, and the
    /// machine is part of what makes them comparable.
    #[must_use]
    pub fn filename(&self) -> String {
        let (year, month, day, hour, minute, second) = parts(self.unix);
        let host: String = self
            .host
            .chars()
            .map(|c| if c.is_ascii_alphanumeric() || c == '-' || c == '_' { c } else { '-' })
            .collect();
        format!("{year:04}-{month:02}-{day:02}-{hour:02}{minute:02}{second:02}-{host}.md")
    }
}

/// One function coverage sweep, as it is written down and read back.
///
/// This is the whole of what a sweep leaves behind for the page. The failing calls themselves are
/// not in it and are not meant to be: they go to whoever ran the sweep, in full and one per line,
/// and what belongs in a series is the counts and enough provenance to say what they are counts of.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Sweep {
    /// When the sweep ran, in UTC.
    pub stamp: String,
    /// The machine it ran on.
    pub host: String,
    /// The rudb version it put the calls to.
    pub rudb: String,
    /// The commit that rudb was built from.
    pub rudb_commit: String,
    /// The commit of this harness, with a note when the tree was dirty.
    pub compat_commit: String,
    /// What the DuckDB on the other side of it called itself.
    pub duckdb_version: String,
    /// Over the distinct function names.
    pub names: Tally,
    /// Over the overload rows.
    pub overloads: Tally,
    /// How many calls made an engine come apart rather than answer.
    pub crashes: usize,
    /// How many overloads each untested reason accounts for, in the order they are printed.
    pub reasons: Vec<(Untested, usize)>,
}

impl Sweep {
    /// The most recent sweep recorded beside the pages in a directory, if there is one.
    ///
    /// The last row that parses, read from the bottom, so the header and any row a half written file
    /// left behind are stepped over rather than reported. No sweep at all is nothing rather than an
    /// error, because a machine that has never run one is the ordinary case and a page still comes
    /// out of it.
    #[must_use]
    pub fn latest(dir: &Path) -> Option<Self> {
        let text = std::fs::read_to_string(dir.join(SWEEPS)).ok()?;
        text.lines().rev().find_map(Self::parse)
    }

    /// One row of the file, back into the counts it was written from.
    fn parse(row: &str) -> Option<Self> {
        let fields: Vec<&str> = row.split('\t').collect();
        if fields.len() != SWEEP_COLUMNS.len() {
            return None;
        }
        let mut reasons = Vec::with_capacity(Untested::ALL.len());
        for why in Untested::ALL {
            reasons.push((why, number(&fields, column(why))?));
        }
        Some(Self {
            stamp: word(&fields, "when")?.to_owned(),
            host: word(&fields, "machine")?.to_owned(),
            rudb: word(&fields, "rudb")?.to_owned(),
            rudb_commit: word(&fields, "rudb_commit")?.to_owned(),
            compat_commit: word(&fields, "compat_commit")?.to_owned(),
            duckdb_version: word(&fields, "duckdb")?.to_owned(),
            names: tally(&fields, "names")?,
            overloads: tally(&fields, "overloads")?,
            crashes: number(&fields, "crashes")?,
            reasons,
        })
    }

    /// Whether this sweep measured the same engine on the same machine as the run beside it.
    ///
    /// Two numbers on one page that came from two different builds are two facts and not one
    /// measurement, and the page has to say so where it happens rather than leave a reader to
    /// compare two commits in the provenance block themselves.
    #[must_use]
    pub fn matches(&self, p: &Provenance) -> bool {
        self.rudb_commit == p.rudb_commit && self.host == p.host
    }
}

/// Which column of the sweep file an untested reason is counted in.
const fn column(why: Untested) -> &'static str {
    match why {
        Untested::NoBoundarySet => "no_boundary",
        Untested::KindNotCalled => "kind_not_called",
        Untested::Volatile => "volatile",
    }
}

/// One named field of a row, or nothing when the name is not a column.
fn word<'a>(fields: &[&'a str], name: &str) -> Option<&'a str> {
    let at = SWEEP_COLUMNS.iter().position(|column| *column == name)?;
    fields.get(at).copied()
}

/// One named field of a row as a count.
fn number(fields: &[&str], name: &str) -> Option<usize> {
    word(fields, name)?.parse().ok()
}

/// The four columns of one tally, which are its name and its name with three suffixes.
fn tally(fields: &[&str], what: &str) -> Option<Tally> {
    Some(Tally {
        total: number(fields, what)?,
        passed: number(fields, &format!("{what}_passed"))?,
        failed: number(fields, &format!("{what}_failed"))?,
        untested: number(fields, &format!("{what}_untested"))?,
    })
}

/// The page itself.
///
/// A [`fmt::Display`] rather than a function that returns a string, because then the tests read the
/// same page the file gets and there is no second rendering path that could differ from it.
#[derive(Debug)]
pub struct Page<'a> {
    run: &'a Isolated,
    provenance: &'a Provenance,
    sweep: Option<&'a Sweep>,
}

impl<'a> Page<'a> {
    /// The page for one corpus run.
    #[must_use]
    pub const fn of(run: &'a Isolated, provenance: &'a Provenance) -> Self {
        Self { run, provenance, sweep: None }
    }

    /// The same page with the most recent function sweep carried onto it.
    ///
    /// Optional because a machine that has never run one still gets a page, and function coverage
    /// goes back to being named under the numbers nothing measures yet rather than being left off.
    #[must_use]
    pub const fn with(mut self, sweep: Option<&'a Sweep>) -> Self {
        self.sweep = sweep;
        self
    }
}

impl fmt::Display for Page<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let run = self.run;
        let p = self.provenance;
        writeln!(f, "# rudb against DuckDB")?;
        writeln!(f)?;
        writeln!(
            f,
            "Written by `rudb-compat report` at {}. This page is generated and never edited by hand, so anything wrong on it is wrong in the harness.",
            p.stamp
        )?;
        writeln!(f)?;
        writeln!(
            f,
            "Every number here has the denominator it was computed over printed beside it, there is no single headline percentage anywhere on it, and the numbers nothing measures yet are listed under a heading of their own rather than left out. The provenance of the whole run is at the bottom."
        )?;
        writeln!(f)?;

        writeln!(f, "## The corpus")?;
        writeln!(f)?;
        if p.upstream {
            writeln!(
                f,
                "DuckDB's own sqllogictest suite at {}, run against {} at {}.",
                p.corpus_ref, p.rudb, p.rudb_commit
            )?;
        } else {
            writeln!(
                f,
                "The files under {}, which is not the upstream corpus, run against {} at {}. The numbers below are about that directory and they are not the published number.",
                p.corpus_path, p.rudb, p.rudb_commit
            )?;
        }
        writeln!(f)?;
        writeln!(f, "    files       {:>7}", run.files)?;
        writeln!(f, "    attempted   {:>7}  records that ran", run.attempted())?;
        writeln!(f, "    passed      {:>7}", run.passed)?;
        writeln!(f, "    failed      {:>7}", run.failed)?;
        writeln!(f, "    pass rate   {:>6.1} percent of attempted", run.rate() * 100.0)?;
        writeln!(f)?;
        writeln!(
            f,
            "{} records were not attempted at all and none of them are in the rate above. That is the number to read beside the rate, because a runner that skips everything it would fail reports a hundred percent.",
            run.skips.total()
        )?;
        writeln!(f)?;
        for (gap, count) in run.skips.by_gap() {
            writeln!(f, "    {count:>7}  {:<10}{}", gap.name(), gap.blurb())?;
        }
        writeln!(f)?;
        let files = run.skipped_files.len();
        let cut = run.stopped.len();
        writeln!(
            f,
            "    {files:>7}  not run   files the runner never opened, whose records are on the rows above"
        )?;
        writeln!(
            f,
            "    {cut:>7}  cut off   files killed part way through, whose records are in neither column"
        )?;
        writeln!(f)?;

        writeln!(f, "## Failures by reason")?;
        writeln!(f)?;
        writeln!(
            f,
            "All nine reasons, including the ones at zero, because this page is read as a series and a row that comes and goes is a row nobody can follow. The shape of this list says more than the pass rate does: fifty thousand not implemented and fifty wrong answers is a young engine, and the other way round at the same rate is a crisis."
        )?;
        writeln!(f)?;
        let reasons = run.reasons();
        for reason in Reason::ALL {
            writeln!(
                f,
                "    {:>7}  {:<16}{}",
                reasons.count(reason),
                reason.name(),
                reason.blurb()
            )?;
        }
        writeln!(f)?;
        let wrong = reasons.count(Reason::WrongAnswer);
        if wrong == 0 {
            writeln!(f, "No wrong answers, which is the row that matters.")?;
        } else {
            writeln!(f, "{wrong} wrong answers, every one of them a bug at priority p0.")?;
        }
        writeln!(f)?;

        if let Some(sweep) = self.sweep {
            writeln!(f, "## Function coverage")?;
            writeln!(f)?;
            writeln!(
                f,
                "Not measured by this run. The sweep behind this number puts every generated call to every overload in duckdb_functions() to both engines and takes about forty minutes, and this page comes out of a corpus run, so the number below is the most recent sweep written down beside these pages and it is carried here rather than computed here."
            )?;
            writeln!(f)?;
            let line = |f: &mut fmt::Formatter<'_>, what: &str, tally: &Tally| {
                writeln!(
                    f,
                    "    {what:<12}{:>6} of {:<6}{:>5.1} percent, with {} failed and {} never tested",
                    tally.passed,
                    tally.total,
                    tally.share() * 100.0,
                    tally.failed,
                    tally.untested
                )
            };
            line(f, "names", &sweep.names)?;
            line(f, "overloads", &sweep.overloads)?;
            writeln!(f)?;
            writeln!(
                f,
                "An overload that was never tested is a gap in this harness rather than a gap in the engine, and there are three of those. They are counted against the denominator all the same, because a name nothing tested is a name nobody can claim."
            )?;
            writeln!(f)?;
            for (why, count) in &sweep.reasons {
                writeln!(f, "    {count:>7}  {}", why.name())?;
            }
            writeln!(f)?;
            if sweep.crashes > 0 {
                writeln!(
                    f,
                    "{} calls made one of the two engines panic rather than answer, and every one of those is a bug in the engine that panicked rather than a difference between the two.",
                    sweep.crashes
                )?;
                writeln!(f)?;
            }
            writeln!(
                f,
                "This is the unweighted number. The weighted one section 1.1 also asks for needs the real query corpus to weight by, and that corpus does not exist yet."
            )?;
            writeln!(f)?;
            writeln!(f, "    measured    {} on {}", sweep.stamp, sweep.host)?;
            writeln!(f, "    engine      {} at {}", sweep.rudb, sweep.rudb_commit)?;
            writeln!(f, "    rudb-compat {}", sweep.compat_commit)?;
            writeln!(f, "    duckdb      {}", sweep.duckdb_version)?;
            writeln!(f)?;
            if sweep.matches(p) {
                writeln!(
                    f,
                    "That is the same engine build on the same machine as the corpus numbers above, so this page is one measurement."
                )?;
            } else {
                writeln!(
                    f,
                    "That is not the engine build and machine the corpus numbers above came from, so the two halves of this page are two measurements and not one."
                )?;
            }
            writeln!(f)?;
        }

        writeln!(f, "## What this page does not say yet")?;
        writeln!(f)?;
        writeln!(
            f,
            "Eleven numbers belong here, per section 11.2. These are the ones nothing computes today, each with the denominator it will be computed over and what has to exist before it can be. None of them is printed as a zero, because a zero is a measurement and these are not measured."
        )?;
        writeln!(f)?;
        for (what, needs) in MISSING {
            if what == FUNCTIONS && self.sweep.is_some() {
                continue;
            }
            writeln!(f, "    {what:<20}{needs}")?;
        }
        writeln!(f)?;

        writeln!(f, "## Provenance")?;
        writeln!(f)?;
        writeln!(f, "    when           {}", p.stamp)?;
        writeln!(f, "    machine        {}, {}", p.host, p.platform)?;
        writeln!(f, "    engine         {} at {}", p.rudb, p.rudb_commit)?;
        writeln!(f, "    rudb-compat    {}", p.compat_commit)?;
        writeln!(f, "    duckdb pin     {}", p.duckdb_pin)?;
        writeln!(f, "    duckdb binary  {}", p.duckdb_binary)?;
        writeln!(f, "    duckdb version {}", p.duckdb_version)?;
        writeln!(f, "    duckdb md5     {}", p.duckdb_hash)?;
        writeln!(f, "    duckdb pinned  {}", p.duckdb_pinned)?;
        if p.upstream {
            writeln!(f, "    corpus         {} at {}", p.corpus_ref, p.corpus_commit)?;
        } else {
            writeln!(f, "    corpus         not the upstream corpus")?;
        }
        writeln!(f, "    corpus path    {}", p.corpus_path)?;
        writeln!(f, "    seed           {}", p.seed)?;
        Ok(())
    }
}

/// The row of [`MISSING`] that a recorded sweep takes off the list.
const FUNCTIONS: &str = "function coverage";

/// The four numbers section 11.2 asks for that nothing here computes yet.
///
/// Kept as data rather than as paragraphs so that deleting a row is the whole of the work when one
/// of them starts being measured, and so that a reader can see there are four of them. Function
/// coverage is still on the list, because a page written on a machine that has never run a sweep has
/// nothing to carry and the honest thing to print then is what it would take.
const MISSING: [(&str, &str); 4] = [
    ("statement coverage", "over the 36 statements in section 1.1, needs the per statement suite"),
    (
        FUNCTIONS,
        "over the 1159 names in duckdb_functions() on the pin, weighted and unweighted, needs a sweep beside these pages, which `rudb-compat coverage --out` writes",
    ),
    (
        "error levels",
        "five levels over the records where the pinned binary errored, needs the error comparison in section 8.2",
    ),
    (
        "resource ratios",
        "rudb over duckdb on time, processor time and peak resident set, as medians with the quartiles, over the whole corpus and per feature and over the worst twenty records, needs a corpus run that measures",
    ),
];

/// The header line of the series file.
#[must_use]
pub fn header() -> String {
    COLUMNS.join("\t")
}

/// The header line of the sweep file.
#[must_use]
pub fn sweep_header() -> String {
    SWEEP_COLUMNS.join("\t")
}

/// One sweep as a row of that file.
///
/// The same fields in the same order as [`SWEEP_COLUMNS`], which a test checks, and which
/// [`Sweep::parse`] reads back by name rather than by position so that the two cannot drift apart
/// without the test noticing first.
#[must_use]
pub fn sweep_row(coverage: &Coverage, p: &Provenance) -> String {
    let mut fields = vec![
        p.stamp.clone(),
        p.host.clone(),
        p.rudb.clone(),
        p.rudb_commit.clone(),
        p.compat_commit.clone(),
        p.duckdb_version.clone(),
    ];
    for tally in [&coverage.names, &coverage.overloads] {
        fields.push(tally.total.to_string());
        fields.push(tally.passed.to_string());
        fields.push(tally.failed.to_string());
        fields.push(tally.untested.to_string());
    }
    fields.push(coverage.crashes.to_string());
    for why in Untested::ALL {
        let count = coverage.reasons.iter().find(|(one, _)| *one == why).map_or(0, |(_, n)| *n);
        fields.push(count.to_string());
    }
    fields.join("\t")
}

/// One run as a row of the series file.
///
/// The same fields in the same order as [`COLUMNS`], which a test checks, because a row that has
/// drifted from its header is worse than no row at all.
#[must_use]
pub fn row(run: &Isolated, p: &Provenance) -> String {
    let skips = run.skips;
    let fields = [
        p.stamp.clone(),
        p.host.clone(),
        p.rudb.clone(),
        p.rudb_commit.clone(),
        p.compat_commit.clone(),
        p.corpus_commit.clone(),
        p.duckdb_version.clone(),
        run.files.to_string(),
        run.attempted().to_string(),
        run.passed.to_string(),
        run.failed.to_string(),
        format!("{:.3}", run.rate()),
        (skips.conditional + skips.mode + skips.maybe).to_string(),
        skips.engine.to_string(),
        (skips.unsupported + skips.unreadable).to_string(),
        skips.machine.to_string(),
        run.reasons().count(Reason::WrongAnswer).to_string(),
    ];
    fields.join("\t")
}

/// Write the page and append the row, and say where the page went.
///
/// The page is a new file every run and the series is appended to, which is section 11.4 made
/// mechanical: a page that is overwritten cannot go down in front of anybody, and a number that is
/// allowed to go down has to be one somebody can watch going down.
///
/// # Errors
///
/// When the directory cannot be made or either file cannot be written.
pub fn write(
    dir: &Path,
    run: &Isolated,
    p: &Provenance,
    sweep: Option<&Sweep>,
) -> Result<PathBuf, HarnessError> {
    std::fs::create_dir_all(dir)
        .map_err(|e| HarnessError::new(format!("cannot make {}: {e}", dir.display())))?;
    let page = dir.join(p.filename());
    std::fs::write(&page, Page::of(run, p).with(sweep).to_string())
        .map_err(|e| HarnessError::new(format!("cannot write {}: {e}", page.display())))?;
    append(&dir.join(SERIES), &header(), &row(run, p))?;
    Ok(page)
}

/// Write one function sweep down beside the pages, and say which file it went in.
///
/// No page of its own. A sweep is a handful of counts and a great many failing calls, the calls go
/// to whoever ran it, and the counts belong on the page the corpus run writes rather than on a
/// second page nobody would read beside the first.
///
/// # Errors
///
/// When the directory cannot be made or the file cannot be appended to.
pub fn record(dir: &Path, coverage: &Coverage, p: &Provenance) -> Result<PathBuf, HarnessError> {
    std::fs::create_dir_all(dir)
        .map_err(|e| HarnessError::new(format!("cannot make {}: {e}", dir.display())))?;
    let file = dir.join(SWEEPS);
    append(&file, &sweep_header(), &sweep_row(coverage, p))?;
    Ok(file)
}

/// Add one row to a file, starting it with its header when it is not there yet.
fn append(path: &Path, header: &str, row: &str) -> Result<(), HarnessError> {
    use std::io::Write as _;
    let fresh = !path.exists();
    let mut file = std::fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(path)
        .map_err(|e| HarnessError::new(format!("cannot open {}: {e}", path.display())))?;
    let text = if fresh { format!("{header}\n{row}\n") } else { format!("{row}\n") };
    file.write_all(text.as_bytes())
        .map_err(|e| HarnessError::new(format!("cannot write {}: {e}", path.display())))
}

/// The commit a lock file pins the engine at.
///
/// Read out of `Cargo.lock` rather than asked of the engine, because the engine does not know which
/// commit it was built from and the lock file is the thing that decided. A tree whose lock has
/// moved since the binary was built reports the lock, which is wrong for about the length of one
/// build and is the closest thing to the truth that is available here.
#[must_use]
pub fn locked(root: &Path) -> Option<String> {
    let text = std::fs::read_to_string(root.join("Cargo.lock")).ok()?;
    pinned(&text).map(|commit| short(&commit).to_owned())
}

/// The commit out of the text of a lock file.
fn pinned(lock: &str) -> Option<String> {
    let mut in_rudb = false;
    for line in lock.lines() {
        let line = line.trim();
        if line == "[[package]]" {
            in_rudb = false;
        }
        if line == "name = \"rudb\"" {
            in_rudb = true;
        }
        if in_rudb && line.starts_with("source = ") {
            return line.rsplit_once('#').map(|(_, commit)| commit.trim_matches('"').to_owned());
        }
    }
    None
}

/// The commit this harness is at, and whether the tree it ran from was clean.
///
/// A dirty tree is said out loud rather than hidden, because a page from a dirty tree cannot be
/// reproduced from the commit it names and a reader has no other way of knowing that.
fn checkout(root: &Path) -> String {
    let Some(commit) = git(root, &["rev-parse", "HEAD"]) else {
        return "unknown, this is not a checkout".to_owned();
    };
    match git(root, &["status", "--porcelain"]) {
        Some(changes) if !changes.is_empty() => format!("{}, dirty", short(&commit)),
        Some(_) => format!("{}, clean", short(&commit)),
        None => short(&commit).to_owned(),
    }
}

/// Run git in a directory and give back what it said, or nothing when it failed.
fn git(root: &Path, args: &[&str]) -> Option<String> {
    let out = Command::new("git")
        .arg("-C")
        .arg(root)
        .args(args)
        .output()
        .ok()
        .filter(|out| out.status.success())?;
    Some(String::from_utf8_lossy(&out.stdout).trim().to_owned())
}

/// The first ten characters of a commit, which is what the page prints.
fn short(commit: &str) -> &str {
    let at = commit.char_indices().nth(10).map_or(commit.len(), |(at, _)| at);
    &commit[..at]
}

/// The md5 of a file, for the binary the run measured against.
///
/// Two builds of the same DuckDB commit with different flags call themselves the same version and
/// are not the same binary, and a resource ratio against one of them is not a resource ratio
/// against the other.
fn md5_of(path: &Path) -> String {
    match std::fs::read(path) {
        Ok(bytes) => crate::hash::md5_hex(&bytes),
        Err(e) => format!("cannot read the binary: {e}"),
    }
}

/// What the machine calls itself.
fn host() -> String {
    Command::new("hostname")
        .output()
        .ok()
        .filter(|out| out.status.success())
        .map(|out| String::from_utf8_lossy(&out.stdout).trim().to_owned())
        .filter(|name| !name.is_empty())
        .unwrap_or_else(|| "unknown".to_owned())
}

/// The operating system, the processor and the cores the run could see.
fn platform() -> String {
    let cores = std::thread::available_parallelism().map_or(0, std::num::NonZero::get);
    format!("{} {}, {cores} cores", std::env::consts::OS, std::env::consts::ARCH)
}

/// An instant written out, in UTC, to the second.
///
/// UTC and not local time because these rows are compared across four machines that are not all in
/// one place, and a series whose rows are each in their own time zone is not ordered.
#[must_use]
pub fn stamp(unix: u64) -> String {
    let (year, month, day, hour, minute, second) = parts(unix);
    format!("{year:04}-{month:02}-{day:02} {hour:02}:{minute:02}:{second:02} UTC")
}

/// The year, month, day, hour, minute and second of an instant, in UTC.
///
/// The date part is Howard Hinnant's civil from days, which is the algorithm underneath every date
/// library there is. It is written out here rather than depended on, because this crate has one
/// dependency and it is the engine, and a date on a report is not worth a second one.
fn parts(unix: u64) -> (i64, u32, u32, u64, u64, u64) {
    let days = i64::try_from(unix / 86_400).unwrap_or(0);
    let rest = unix % 86_400;
    let z = days + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let doe = z - era * 146_097;
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365;
    let year = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let day = doy - (153 * mp + 2) / 5 + 1;
    let month = if mp < 10 { mp + 3 } else { mp - 9 };
    let year = if month <= 2 { year + 1 } else { year };
    let month = u32::try_from(month).unwrap_or(1);
    let day = u32::try_from(day).unwrap_or(1);
    (year, month, day, rest / 3600, (rest % 3600) / 60, rest % 60)
}

#[cfg(test)]
mod tests {
    use super::{
        COLUMNS, Page, Provenance, SWEEP_COLUMNS, Sweep, header, parts, pinned, row, short, stamp,
        sweep_header, sweep_row,
    };
    use std::path::Path;

    use crate::conform::{Failure, Reason, Skips};
    use crate::coverage::{Coverage, Tally, Untested};
    use crate::isolate::Isolated;

    fn provenance() -> Provenance {
        Provenance {
            unix: 1_757_836_353,
            stamp: stamp(1_757_836_353),
            host: "server2".to_owned(),
            platform: "linux x86_64, 6 cores".to_owned(),
            rudb: "0.3.6".to_owned(),
            rudb_commit: "cfdf975e68".to_owned(),
            compat_commit: "55cc9e4a2b, clean".to_owned(),
            duckdb_pin: "v2.0 at cc7e7bac7f".to_owned(),
            duckdb_binary: "/usr/local/bin/duckdb".to_owned(),
            duckdb_version: "v2.0.0-dev1234".to_owned(),
            duckdb_hash: "0123456789abcdef0123456789abcdef".to_owned(),
            duckdb_pinned: "yes, this is the commit the grammar is vendored from".to_owned(),
            corpus_ref: "v2.0-cyanoptera".to_owned(),
            corpus_commit: "9f8e7d6c5b".to_owned(),
            corpus_path: "target/corpus/test/sql".to_owned(),
            upstream: true,
            seed: "none, nothing in this run generates anything".to_owned(),
        }
    }

    fn run() -> Isolated {
        Isolated {
            files: 4096,
            passed: 15_920,
            failed: 56_548,
            skips: Skips {
                conditional: 21_000,
                mode: 300,
                maybe: 58,
                unsupported: 0,
                engine: 19_403,
                machine: 66,
                unreadable: 0,
            },
            skipped_files: vec![("a.test".to_owned(), "needs an extension".to_owned())],
            failures: vec![failure(Reason::NotImplemented), failure(Reason::Unbound)],
            stopped: Vec::new(),
        }
    }

    fn failure(reason: Reason) -> Failure {
        Failure {
            file: "a.test".to_owned(),
            line: 1,
            sql: "select 1".to_owned(),
            reason,
            detail: String::new(),
        }
    }

    #[test]
    fn every_number_on_the_page_has_the_thing_it_was_divided_by_next_to_it() {
        let page = Page::of(&run(), &provenance()).to_string();
        assert!(page.contains("attempted     72468  records that ran"), "{page}");
        assert!(page.contains("pass rate     22.0 percent of attempted"), "{page}");
        assert!(page.contains("40827 records were not attempted"), "{page}");
    }

    #[test]
    fn all_nine_failure_reasons_are_on_the_page_including_the_ones_at_zero() {
        let page = Page::of(&run(), &provenance()).to_string();
        for reason in Reason::ALL {
            assert!(page.contains(reason.name()), "{} is not on the page\n{page}", reason.name());
        }
        assert!(page.contains("      0  stopped"), "a reason at zero is left off\n{page}");
    }

    #[test]
    fn the_numbers_nothing_measures_yet_are_named_rather_than_left_off_or_called_zero() {
        let page = Page::of(&run(), &provenance()).to_string();
        for missing in
            ["statement coverage", "function coverage", "error levels", "resource ratios"]
        {
            assert!(page.contains(missing), "{missing} is not named\n{page}");
        }
        assert!(page.contains("What this page does not say yet"), "{page}");
    }

    /// The numbers off the first full sweep, which ran on server2 in September.
    fn measured() -> Coverage {
        Coverage {
            names: Tally { total: 1159, passed: 16, failed: 622, untested: 521 },
            overloads: Tally { total: 3245, passed: 42, failed: 1386, untested: 1817 },
            reasons: vec![
                (Untested::NoBoundarySet, 245),
                (Untested::KindNotCalled, 1538),
                (Untested::Volatile, 34),
            ],
            crashes: 12,
            failing: vec![("add".to_owned(), 42, 43)],
        }
    }

    fn sweep() -> Sweep {
        Sweep::parse(&sweep_row(&measured(), &provenance())).expect("the row it just wrote")
    }

    #[test]
    fn a_sweep_beside_the_pages_puts_the_function_coverage_number_on_one() {
        let sweep = sweep();
        let page = Page::of(&run(), &provenance()).with(Some(&sweep)).to_string();
        assert!(page.contains("## Function coverage"), "{page}");
        assert!(page.contains("16 of 1159"), "the number is not beside what it is over\n{page}");
        assert!(page.contains("1.4 percent, with 622 failed and 521 never tested"), "{page}");
        assert!(page.contains("42 of 3245"), "{page}");
        assert!(page.contains("1.3 percent, with 1386 failed and 1817 never tested"), "{page}");
        assert!(page.contains("1538  a kind the generator does not call yet"), "{page}");
        assert!(page.contains("12 calls made one of the two engines panic"), "{page}");
        assert!(page.contains("unweighted"), "{page}");
    }

    #[test]
    fn the_number_a_sweep_carried_is_not_named_as_one_nothing_measures() {
        let sweep = sweep();
        let page = Page::of(&run(), &provenance()).with(Some(&sweep)).to_string();
        let missing = page.split("## What this page does not say yet").nth(1).expect("the heading");
        assert!(!missing.contains("function coverage"), "{missing}");
        for still in ["statement coverage", "error levels", "resource ratios"] {
            assert!(missing.contains(still), "{still} came off the list too\n{missing}");
        }
    }

    #[test]
    fn a_sweep_from_another_build_says_it_is_not_the_same_measurement() {
        let same = sweep();
        let page = Page::of(&run(), &provenance()).with(Some(&same)).to_string();
        assert!(page.contains("so this page is one measurement"), "{page}");

        let mut other = sweep();
        other.rudb_commit = "0000000000".to_owned();
        let page = Page::of(&run(), &provenance()).with(Some(&other)).to_string();
        assert!(page.contains("two measurements and not one"), "{page}");
    }

    #[test]
    fn a_run_with_nothing_crashing_leaves_the_crash_sentence_off_the_page() {
        let mut quiet = measured();
        quiet.crashes = 0;
        let sweep = Sweep::parse(&sweep_row(&quiet, &provenance())).expect("a row");
        let page = Page::of(&run(), &provenance()).with(Some(&sweep)).to_string();
        assert!(!page.contains("panic"), "{page}");
    }

    #[test]
    fn a_sweep_row_has_exactly_the_fields_its_header_says_it_has() {
        let row = sweep_row(&measured(), &provenance());
        assert_eq!(sweep_header().split('\t').count(), SWEEP_COLUMNS.len());
        assert_eq!(row.split('\t').count(), SWEEP_COLUMNS.len(), "{row}");
        assert!(!row.contains('\n'), "a row that is two rows\n{row}");
    }

    #[test]
    fn a_sweep_reads_back_as_the_counts_it_was_written_from() {
        let coverage = measured();
        let sweep = sweep();
        assert_eq!(sweep.names, coverage.names);
        assert_eq!(sweep.overloads, coverage.overloads);
        assert_eq!(sweep.reasons, coverage.reasons);
        assert_eq!(sweep.crashes, coverage.crashes);
        assert_eq!(sweep.host, "server2");
        assert_eq!(sweep.rudb_commit, "cfdf975e68");
    }

    #[test]
    fn a_row_that_is_not_one_is_stepped_over_rather_than_read_as_zeroes() {
        assert_eq!(Sweep::parse(&sweep_header()), None, "the header is not a sweep");
        assert_eq!(Sweep::parse(""), None);
        let short = sweep_row(&measured(), &provenance()).replace("\t12\t", "\t");
        assert_eq!(Sweep::parse(&short), None, "a row missing a field is not half a sweep");
    }

    #[test]
    fn the_last_sweep_written_is_the_one_that_comes_back() {
        let dir = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("target")
            .join(format!("sweep-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        assert_eq!(Sweep::latest(&dir), None, "a machine that never swept carries nothing");

        let mut older = measured();
        older.names.passed = 1;
        super::record(&dir, &older, &provenance()).expect("a directory it can make");
        super::record(&dir, &measured(), &provenance()).expect("the same directory again");

        let read = Sweep::latest(&dir).expect("two of them were written");
        assert_eq!(read.names.passed, 16, "the older one came back");
        let text = std::fs::read_to_string(dir.join(super::SWEEPS)).expect("the file");
        assert_eq!(text.lines().count(), 3, "a header and two rows\n{text}");
        assert!(text.starts_with(&sweep_header()), "{text}");
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn the_page_carries_the_commits_and_the_machine_the_run_happened_on() {
        let p = provenance();
        let page = Page::of(&run(), &p).to_string();
        for field in [
            &p.stamp,
            &p.host,
            &p.rudb_commit,
            &p.compat_commit,
            &p.duckdb_pin,
            &p.duckdb_hash,
            &p.duckdb_pinned,
            &p.corpus_commit,
            &p.seed,
        ] {
            assert!(page.contains(field.as_str()), "{field} is not on the page\n{page}");
        }
    }

    #[test]
    fn a_run_with_a_wrong_answer_in_it_says_so_where_a_clean_one_says_there_were_none() {
        let clean = Page::of(&run(), &provenance()).to_string();
        assert!(clean.contains("No wrong answers, which is the row that matters."), "{clean}");
        let mut wrong = run();
        wrong.failures.push(failure(Reason::WrongAnswer));
        let page = Page::of(&wrong, &provenance()).to_string();
        assert!(
            page.contains("1 wrong answers, every one of them a bug at priority p0."),
            "{page}"
        );
    }

    #[test]
    fn a_page_from_a_directory_somebody_named_says_it_is_not_the_published_number() {
        let mut p = provenance();
        p.upstream = false;
        p.corpus_path = "corpus/slt".to_owned();
        let page = Page::of(&run(), &p).to_string();
        assert!(page.contains("which is not the upstream corpus"), "{page}");
        assert!(page.contains("they are not the published number"), "{page}");
        assert!(page.contains("corpus         not the upstream corpus"), "{page}");
        let upstream = Page::of(&run(), &provenance()).to_string();
        assert!(
            upstream.contains("DuckDB's own sqllogictest suite at v2.0-cyanoptera"),
            "{upstream}"
        );
        assert!(!upstream.contains("not the published number"), "{upstream}");
    }

    #[test]
    fn the_page_keeps_the_prose_rules_it_asks_everything_else_in_this_repository_to_keep() {
        let page = Page::of(&run(), &provenance()).to_string();
        assert!(!page.contains('\u{2014}') && !page.contains('\u{2013}'), "an em or en dash");
        let lines: Vec<&str> = page.lines().collect();
        for (at, line) in lines.iter().enumerate() {
            assert!(line.trim() != "---", "a horizontal rule on line {}", at + 1);
            let prose = !line.is_empty() && !line.starts_with([' ', '#', '-']);
            let next = lines.get(at + 1).copied().unwrap_or("");
            let continued = !next.is_empty() && !next.starts_with([' ', '#', '-']);
            assert!(!(prose && continued), "a sentence across two lines at {}", at + 1);
        }
    }

    #[test]
    fn a_row_of_the_series_has_exactly_the_fields_its_header_says_it_has() {
        let header = header();
        let row = row(&run(), &provenance());
        assert_eq!(header.split('\t').count(), COLUMNS.len());
        assert_eq!(row.split('\t').count(), COLUMNS.len(), "{row}");
        assert!(!row.contains('\n'), "a row that is two rows\n{row}");
    }

    #[test]
    fn the_row_counts_the_skips_the_same_way_the_page_does() {
        let run = run();
        let row = row(&run, &provenance());
        let fields: Vec<&str> = row.split('\t').collect();
        let at = |name: &str| COLUMNS.iter().position(|c| *c == name).expect("a column");
        assert_eq!(fields[at("skip_excused")], "21358");
        assert_eq!(fields[at("skip_engine")], "19403");
        assert_eq!(fields[at("skip_harness")], "0");
        assert_eq!(fields[at("skip_machine")], "66");
        assert_eq!(fields[at("wrong_answers")], "0");
    }

    #[test]
    fn the_file_a_run_writes_is_named_after_when_it_ran_and_where() {
        let p = provenance();
        assert_eq!(p.filename(), "2025-09-14-075233-server2.md");
    }

    #[test]
    fn a_machine_whose_name_would_make_a_path_does_not_get_to() {
        let mut p = provenance();
        p.host = "some/host name".to_owned();
        assert_eq!(p.filename(), "2025-09-14-075233-some-host-name.md");
    }

    #[test]
    fn an_instant_is_written_out_in_utc_and_to_the_second() {
        assert_eq!(stamp(0), "1970-01-01 00:00:00 UTC");
        assert_eq!(stamp(1_000_000_000), "2001-09-09 01:46:40 UTC");
        assert_eq!(stamp(1_757_836_353), "2025-09-14 07:52:33 UTC");
        // The leap day, which is the one the arithmetic gets wrong when it is written by hand.
        assert_eq!(parts(1_709_164_800), (2024, 2, 29, 0, 0, 0));
    }

    #[test]
    fn the_commit_the_lock_file_pins_the_engine_at_is_read_out_of_it() {
        let lock = "\
[[package]]
name = \"rudb-arrow\"
version = \"0.3.6\"
source = \"git+https://github.com/tamnd/rudb?branch=main#aaaaaaaaaaaaaaaa\"

[[package]]
name = \"rudb\"
version = \"0.3.6\"
source = \"git+https://github.com/tamnd/rudb?branch=main#cfdf975e68baab143facaadcde8445b8e93b42f8\"
";
        assert_eq!(pinned(lock).as_deref(), Some("cfdf975e68baab143facaadcde8445b8e93b42f8"));
    }

    #[test]
    fn a_lock_file_with_no_engine_in_it_says_nothing_rather_than_guessing() {
        assert_eq!(pinned("[[package]]\nname = \"something\"\nversion = \"1.0\"\n"), None);
    }

    #[test]
    fn a_commit_is_shortened_without_falling_over_a_short_one() {
        assert_eq!(short("cfdf975e68baab143facaadcde8445b8e93b42f8"), "cfdf975e68");
        assert_eq!(short("abc"), "abc");
        assert_eq!(short(""), "");
    }
}
